version: '3.8'

services:
  pgvector-db:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: feed_ranking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: victoria

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  nest-api:
    build: .
    container_name: nest-api
    depends_on:
      - pgvector-db
      - redis
    ports:
      - "3001:3000"
    env_file:
      - .env
